name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.12"
      - run: uvx prek run --all-files --show-diff-on-failure

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: bazel run --config=ci gazelle.check
      - run: bazel test --config=ci //...
      - run: bazel run --config=ci //tools:bazel_env print-path >> "$GITHUB_PATH"
      - run: which aws && aws --version

  devcontainer-build:
    name: Build and test in devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Build and run tests in devcontainer
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        with:
          push: never
          runCmd: |
            bazel run --config=ci gazelle.check
            bazel test --config=ci //...
            bazel run --config=ci //tools:bazel_env print-path
